<%! String title = "Income"; %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="function/head.jsp" %>
<%@ taglib prefix="sidebar" uri="/WEB-INF/sidebar.tld" %>
<%@ taglib prefix="content" uri="/WEB-INF/content.tld" %>
<%@ taglib prefix="alert" uri="/WEB-INF/alert.tld" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:useBean id="user" type="it.itp4511.ea.bean.UserBean" scope="session"/>

<!--Menu-->
<sidebar:menu href="${pageContext.request.contextPath}">
    <sidebar:parentItem name="Venue Booking">
        <sidebar:item href="${pageContext.request.contextPath}">Book Venue</sidebar:item> <!--All user can see-->
        <sidebar:item href="${pageContext.request.contextPath}/venue/yourBooking.jsp">Your Booking</sidebar:item> <!--All user can see-->
    </sidebar:parentItem>
    <sidebar:parentItem name="Venue Management">
        <sidebar:item href="${pageContext.request.contextPath}/venue">View Venue</sidebar:item> <!--Only Admin and Operator can see-->
        <sidebar:item href="${pageContext.request.contextPath}/venue/create">Create Venue</sidebar:item> <!--Only Admin and Operator can see-->
        <sidebar:item href="${pageContext.request.contextPath}/venue/booking">View Booking</sidebar:item> <!--Only Admin and Operator can see-->
    </sidebar:parentItem>
    <sidebar:parentItem name="Account Management">
        <sidebar:item href="${pageContext.request.contextPath}/admin/account">View Account</sidebar:item>
        <sidebar:item href="${pageContext.request.contextPath}/admin/account/create">Create Account</sidebar:item>
    </sidebar:parentItem>
    <sidebar:parentItem name="Analytic">
        <sidebar:item href="${pageContext.request.contextPath}/bookingRate.jsp">Booking Rate</sidebar:item>
        <sidebar:item href="${pageContext.request.contextPath}/bookingAttendance.jsp">Booking Attendance</sidebar:item>
    </sidebar:parentItem>
    <sidebar:parentItem name="Report" active="true">
        <sidebar:item href="${pageContext.request.contextPath}/income.jsp" active="true">Income</sidebar:item>
    </sidebar:parentItem>
</sidebar:menu>

<content:main>
    <content:header>
        <content:directory pageTitle="<%=title%>">
            <li><a href="">Report</a></li>
            <li><span>Income</span></li>
        </content:directory>
        <content:profile username="${user.username}"/>
    </content:header>
    <content:content>
    <div class="row mt-5 mb-5">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-sm-flex justify-content-between align-items-center">
                        <h4 class="header-title mb-0">Income Generated by Venue</h4>
                        <div>
                            <select class="form-select" aria-label="Default select example">
                                <option selected>Select Venue</option>
                                <option value="selectVenue_1">Tuen Mun</option>
                                <option value="selectVenue_2">Sha Tin</option>
                                <option value="selectVenue_3">Tsing Yi</option>
                                <option value="selectVenue_4">Lee Wai Lee</option>
                                <option value="selectVenue_5">Chai Wan</option>
                            </select>
                        </div>
                        <div class="btn-group" role="group" aria-label="Basic outlined example">
                            <button type="button" class="btn btn-outline-primary" id="forMonthly">Monthly</button>
                            <button type="button" class="btn btn-outline-primary" id="forYearly">Yearly</button>
                        </div>
                    </div>

                    <div class="market-status-table mt-4">
                        <div class="table-responsive">
                            <table class="dbkit-table">
                                <tr class="heading-td">
                                    <td>Month</td> <!--gen "Year" text when selected Yearly button-->
                                    <td>Income</td>
                                </tr>
                                <tr>
                                    <td>Jan</td>
                                    <td>$ 446,857</td>
                                </tr>
                            </table></br>
                            <!--只需提取select的場地的預約記錄即可,與年/月 function無關-->
                            <button type="button" class="btn btn-secondary btn-lg btn-rounded me-2" data-bs-toggle="modal" data-bs-target="#exampleModal">Booking Record of Venue</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </content:content>
</content:main>

<div class="modal fade modal-xl" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Booking Record</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="" action="">

                    <div class="table-responsive">
                        <table class="table text-center">
                            <thead class="text-uppercase bg-dark">
                            <tr class="text-white">
                                <th scope="col">Booking ID</th>
                                <th scope="col">Member's Name</th>
                                <th scope="col">Member's Email</th>
                                <th scope="col">Booking Date</th>
                                <th scope="col">State</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Ada Chan</td>
                                <td>ccc@abc.com</td>
                                <td>12/6/2022</td>
                                <td><button type="button" class="btn btn-flat btn-danger mb-3">Reject</button></td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Sara Wu</td>
                                <td>sarawu@abc.com</td>
                                <td>19/5/2022</td>
                                <td><button type="button" class="btn btn-flat btn-success mb-3">Finish</button></td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Winnie Lee</td>
                                <td>winnielee@abc.com</td>
                                <td>31/12/2021</td>
                                <td><button type="button" class="btn btn-flat btn-warning mb-3">Progress</button></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- load this page script -->
<content:script>
    <content:scriptPath path="${pageContext.request.contextPath}/assets/js/page/income.js"/>
</content:script>

<%@ include file="function/footer.jsp" %>
